export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Meta } from "./Meta";
export { default as DiseaseContainer } from "./DiseaseContainer";
export { default as QuestionContainer } from "./QuestionContainer";
export { default as AnswerContainer } from "./AnswerContainer";
export { default as RelatedDiseases } from "./RelatedDiseases";
export { default as ContactForm } from "./ContactForm";
export { default as Ad } from "./Ad";
